version: '3'

services:
  mosquito:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "80:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwd:/mosquitto/config/passwd
  influxdb:
    image: arm32v7/influxdb
    restart: always
    ports:
      - "8090:8086"
    environment:
      - INFLUXDB_DB=Test
      - INFLUXDB_ADMIN_USER=duc1023as
      - INFLUXDB_ADMIN_PASSWORD=doantotnghiep
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=duc1023as
      - INFLUXDB_USER_PASSWORD=doantotnghiep
      - DATABASE_NAME=Area1
      - TABLE_NAME=DataArea1
      - INFLUX_HOST=localhost
      - INFLUX_PORT=8086
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    command: influxd
  python-client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquito
      - influxdb
    environment:
      - URL_MQTT=mosquito
      - PORT=1883
      - USER=mqttBroker
      - PASSWORD=dominhduc
      - URL_AWS=13.115.13.210
      - USER_AWS=mqttBroker
      - PWD_AWS=dominhduc
      - TOPIC_WILL=ESP32/ON
      - TOPIC_WILLZb=Zigbee/ON
      - INFLUXDB_DB=Test
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=duc1023as
      - INFLUXDB_PASSWORD=doantotnghiep
      - DATABASE_NAME=Test
      - TABLE_NAME=DataArea1
      - TABLE_NAME_Zb=DataArea2
    command: python3 main.py
  python-serial:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      -"/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /dev:/dev
    restart: always
    privileged: true
    depends_on:
      - mosquito
    environment:
      - URL_MQTT=mosquito
      - PORT=1883
      - USER=mqttBroker
      - PASSWORD=dominhduc
      - TOPIC_WILLZb=Zigbee/ON
    command: python3 serialXbee.py
# volumes:
#   influxdb-data:
