version: '3'

services:
  mosquito:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "80:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwd:/mosquitto/config/passwd
  influxdb:
    image: arm32v7/influxdb
    restart: always
    ports:
      - "8090:8086"
    environment:
      # - DOCKER_INFLUXDB_INIT_MODE=setup
      # - DOCKER_INFLUXDB_INIT_USERNAME=duc1023as
      # - DOCKER_INFLUXDB_INIT_PASSWORD=doantotnghiep
      # - DOCKER_INFLUXDB_INIT_ORG=HCMUT
      # - DOCKER_INFLUXDB_INIT_BUCKET=Test
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=DtBwUZy5EgIBiK-9LASY9XAxKpVflq7_jT7eb_r-oSabet9czvHUbPGZQeRuIwbb7-k1wCK9qesaC-coZnzyTA==
      # - DOCKER_INFLUXDB_INIT_AUTH_TOKEN=DtBwUZy5EgIBiK-9LASY9XAxKpVflq7_jT7eb_r-oSabet9czvHUbPGZQeRuIwbb7-k1wCK9qesaC-coZnzyTA==
      # - DOCKER_INFLUXDB_INIT_RETENTION=1d
      # - DOCKER_INFLUXDB_INIT_SHARD_DURATION=1h

      - INFLUXDB_DB=Test
      - INFLUXDB_ADMIN_USER=duc1023as
      - INFLUXDB_ADMIN_PASSWORD=doantotnghiep
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=duc1023as
      - INFLUXDB_USER_PASSWORD=doantotnghiep
      - DATABASE_NAME=Area1
      - TABLE_NAME=DataArea1
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./scripts/initDB.sh:/docker-entrypoint-initdb.d/init_influxdb.sh
  python-client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mosquito
      - influxdb
    environment:
      - URL_MQTT=mosquito
      - PORT=1883
      - USER=mqttBroker
      - PASSWORD=dominhduc
      - URL_AWS=broker.hivemq.com
      - INFLUXDB_DB=Test
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=duc1023as
      - INFLUXDB_PASSWORD=doantotnghiep
      - DATABASE_NAME=Area1
      - TABLE_NAME=DataArea1
    command: python3 main.py
# volumes:
#   influxdb-data:
